<a href="https://colab.research.google.com/github/Chanwoong1/recommendation-system-study/blob/main/%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C_%EA%B3%BC%EA%B1%B0%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 연관분석 알고리즘
- 가능한 모든 경우의 수를 탐색해서 지지도, 신뢰도 향상도가 높은 규칙을 찾아내는 방식
  - 상품이 4개일 때, 전체 경우의 수
    - 4C1 = 4
    - 4C2 = 6
    - 4C3 = 4
    - 4C4 = 1
    - 4 + 6 + 4 + 1 = 15

문제점
- 아이템의 증가에 따른 규칙의 수 증가가 기하급수적으로 증가

# Apriori
Apriori는 아이템셋의 증가를 줄이기 위한 방법이다. 기본적인 아이디어는 '빈번한 아이템셋은 하위 아이템셋 또한 빈번할 것이다.' 이며, 이것은 '빈번하지 않은 아이템 셋은 하위 아이템 셋 또한 빈번하지 않을 것이다.'를 이용하여 아이템셋의 증가를 줄이는 방법이다.

1. k개의 item을 가지고 단일 항목 집단 생성 (one-item frequent set)
2. 단일항목집단에서 최소 지지도 이상의 항목만 선택
3. 2에서 선택된 항목만을 대상으로 2개 항목집단 생성
4. 2개 항목 집단에서 최소 지지도 혹은 신뢰도 이상의 항목만 선택
5. 위의 과정을 k개의 k-item frequent set을 생성할 때까지 반복

## 데이터

|**거래번호**|**상품목록**|
|------|---|
|0|우유, 기저귀, 주스|
|1|양상추, 기저귀, 주스|
|2|우유, 양상추, 기저귀, 맥주|
|3|양상추, 맥주|

Matrix로 변형 (sparse matrix)

|거래번호|우유|양상추|기저귀|주스|맥주|
|------|---|---|---|---|---|
|0|1|0|1|1|0|
|1|0|1|1|0|1|
|2|1|1|1|0|1|
|3|0|1|0|0|1|

1. 5개의 item을 가지고 단일항목집단 생성 : 우유, 양상추, 기저귀, 주스, 맥주
2. 단일 항목 집단에서 최소 지지도 이상의 항목만 선택(ex : 최소지지도 0.5)
- P(우유) : 0.5
- P(양상추) : 0.75
- P(기저귀) : 0.75
- ~P(주스) : 0.25~
- P(맥주) : 0.75

3. 2에서 선택된 항목만을 대상으로 2개 항목 집단 생성 {우유, 양상추, 기저귀, 맥주}

4. 2개 항목 집단에서 최소 지지도 이상의 항목만 선택
- ~{우유, 양상추} : 0.25~
- {우유, 기저귀} : 0.5
- ~{우유, 맥주} : 0.25~
- {양상추, 기저귀} : 0.5
- {양상추, 맥주} : 0.75
- {기저귀, 맥주} : 0.5

5. 위의 과정을 k개의 k-item frequent set을 생성할 때까지 반복


장점
- 원리가 간단하여 사용자가 쉽게 이해할 수 있고 의미를 파악할 수 있음
- 유의한 연관성을 갖는 구매패턴을 찾아줌

단점
- 데이터가 클 경우 (item이 많은 경우)에 속도가 느리고 연산량이 많음
- 실제 사용시에 많은 연관상품들이 나타나는 단점이 있음

# FP-Growth

FP-Growth란?

FP Growth는 이전에 언급한 A Priori의 속도 측면의 단점을 개선한 알고리즘.

Apriori와 비슷한 성능을 내지만 FP Tree라는 구조를 사용해서 따른 속도를 가진다는 게 장점. 

하지만 동일하게 발생하는 아이템 셋(frequent itemsets)을 찾는 데는 좋지만 아이템 간의 연관성을 찾는 것은 어렵다는 단점. 

위의 Apriori 예시에서 Confidence라는 방식을 사용했을 때와 {양상추, 기저귀} -> {맥주}와 같은 결과를 얻기는 힘든 것이 FP-Growth의 한계.

1. 모든 거래를 확인하여, 각 아이템마다의 지지도(support)를 계산하고 최소 지지도이상의 아이템만 선택
2. 모든 거래에서 빈도가 높은 아이템 순서대로 순서를 정렬
3. 부모 노드를 중심으로 거래를 자식노드로 추가해주면서 tree를 생성
4. 새로운 아이템이 나올 경우에는 부모노드부터 시작하고, 그렇지 않으면 기존의 노드에서 확장
5. 위의 과정을 모든 거래에 대해 반복하여 FP TREE를 만들고 최소 지지도 이상의 패턴만을 추출

|거래번호|우유|양상추|기저귀|주스|맥주|
|------|---|---|---|---|---|
|0|1|0|1|1|0|
|1|0|1|1|0|1|
|2|1|1|1|0|1|
|3|0|1|0|0|1|

1. 모든 거래를 확인하여, 각 아이템마다 지지도를 계산하고 최소 지지도 이상의 아이템만 선택

2. 모든 거래에서 빈도가 높은 아이템 순서대로 순서 정렬

정렬 전

|**거래번호**|**상품목록**|
|------|---|
|0|<span class="evidence">우유, 기저귀, ~주스~</span>|
|1|양상추, 기저귀, 주스|
|2|<span class="evidence">우유, 양상추, 기저귀, 맥주</span>|
|3|양상추, 맥주|

정렬 후

|**거래번호**|**상품목록**|
|------|---|
|0|<span class="evidence">우유, 기저귀</span>|
|1|양상추, 기저귀, 주스|
|2|<span class="evidence">양상추, 기저귀, 맥주, 우유</span>|
|3|양상추, 맥주|

3. 부모 노드를 중심으로 거래를 자식노드로 추가해주면서 tree를 생성

root - > 기저귀:1 -> 우유 :1

root - > 양상추:1 -> 기저귀:1 -> 맥주 :1

4. 새로운 아이템이 나올 경우에는 부모노드부터 시작하고, 그렇지 않으면 기존의 노드에서 확장

root -> 기저귀:1 -> 우유 :1

root -> **양상추:3** -> **기저귀:2** -> **맥주 :2** -> **우유 : 1**

root -> **양상추:3** -> 맥주:1

5. 지지도가 낮은 순서부터 시작하여, 조건부 패턴을 생성 -> 모든 항목에 대해 반복

|아이템|지지도|Conditional Pattern Bases|
|------|------|-------------------------|
|기저귀|0.75|{양상추} : 2|
|양상추|0.75|{}|
|맥주|0.75|{양상추, 기저귀} : 2, {양상추} : 1|
|우유|0.5|{양상추, 기저귀, 맥주} : 2, {기저귀} : 1|

장점
- Apriori 알고리즘보다 빠르고 2번의 탐색만 필요로 함
- 후보 Itemsets 을 생성할 필요없이 진행 가능

단점
- 대용량의 데이터셋에서 메모리를 효율적으로 사용하지 않음
- Apriori 알고리즘에 비해서 설계하기 어려움
- 지지도의 계산이 FP-Tree가 만들어지고 나서야 가능함

# 실습

In [1]:
!pip install --upgrade mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.19.0)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.1)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.6)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.3->mlxtend) (3.0.0)

In [ ]:
# 0.19.0
print(mlxtend.__version__)

In [2]:
import mlxtend
import numpy as np
import pandas as pd

# 위의 데이터셋 생성
data = np.array([
    ['우유', '기저귀', '쥬스'],             # 0번의 거래
    ['양상추', '기저귀', '맥주'],           # 1번의 거래
    ['우유', '양상추', '기저귀', '맥주'],   # 2번의 거래
    ['양상추', '맥주']                      # 3번의 거래
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # Remove the CWD from sys.path while we load stuff.

In [3]:
from mlxtend.preprocessing import TransactionEncoder    # 희소행렬로 변환
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

     기저귀     맥주    양상추     우유     쥬스
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [4]:
# Apriori
%%time
from mlxtend.frequent_patterns import apriori
display(apriori(df, min_support=0.5, use_colnames=True))

   support        itemsets
0     0.75           (기저귀)
1     0.75            (맥주)
2     0.75           (양상추)
3     0.50            (우유)
4     0.50       (기저귀, 맥주)
5     0.50      (기저귀, 양상추)
6     0.50       (우유, 기저귀)
7     0.75       (양상추, 맥주)
8     0.50  (양상추, 기저귀, 맥주)

CPU times: user 35.7 ms, sys: 933 µs, total: 36.6 ms
Wall time: 60.3 ms

In [7]:
# fp-growth
%%time
# 1.99ms 
from mlxtend.frequent_patterns import fpgrowth
display(fpgrowth(df, min_support=0.5, use_colnames=True))

   support        itemsets
0     0.75           (기저귀)
1     0.50            (우유)
2     0.75           (양상추)
3     0.75            (맥주)
4     0.50       (기저귀, 맥주)
5     0.50      (기저귀, 양상추)
6     0.50  (양상추, 기저귀, 맥주)
7     0.50       (우유, 기저귀)
8     0.75       (양상추, 맥주)

CPU times: user 25.9 ms, sys: 0 ns, total: 25.9 ms
Wall time: 30.6 ms

두 알고리즘에서 속도의 차이가 발생한다.